-- Bu fayl endi jadval YARATISH uchun EMAS — Bot 1'da bu jadvallar allaqachon
-- mavjud. Shunchaki hujjatlashtirish/tekshirish uchun: Bot 2 aynan shu
-- jadvallarga, aynan shu ustunlarga yozadi (manba: Bot 1 HTML fayli,
-- parseAndInsertProduct() funksiyasi).
--
-- catalogs
--   id, name
--
-- product_types
--   id, name, catalog_id (-> catalogs.id)
--
-- products
--   id, name, price, description, catalog_id (-> catalogs.id),
--   type_id (-> product_types.id), images (jsonb: ["url", ...]),
--   extra (jsonb: {"Xususiyat": "Qiymat", ...}),
--   rating (float, default 5.0), reviews_count (int), views_count (int),
--   likes_count (int), sold_count (int)
--
-- product_variants
--   id, product_id (-> products.id), variant_type (masalan "Rang"/"Olcham"),
--   options (jsonb: ["Qora", "Oq", ...])
--
-- reviews
--   id, product_id (-> products.id), author, text, images (jsonb: ["url", ...])
